# Generated by Django 2.2.5 on 2021-06-07 23:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210608_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 23, 20, 56, 117205, tzinfo=utc)),
        ),
    ]
